name: "Event Store"
description: "The open-source, functional database with Complex Event Processing in JavaScript."
url: "http://stage.geteventstore.com"
keywords: "eventstore, event store, event sourcing, ouro, ouroboros, greg young, gregyoung, cqrs, projections"
paginate: 5
markdown: rdiscount
permalink: pretty
pygments: true