name: "Event Store"
description: "The open-source, functional database with Complex Event Processing in JavaScript."
url: "http://stage.geteventstore.com"
paginate: 5
markdown: rdiscount
permalink: pretty
pygments: true