name: "Event Store Documentation"
description: "The open-source, functional database with Complex Event Processing in JavaScript."

url: "http://docs.geteventstore.com"

markdown: rdiscount
permalink: pretty
pygments: true